sudo: required
language: python
python:
  - "3.6"
cache: pip
before_install:
    - pip install -r requirements.txt -t hello_world/build/
    - pip install awscli
    - cp hello_world/*.py hello_world/build/
script:
    #  __  __    _    ____   ____ _____ ____
    # |  \/  |  / \  |  _ \ / ___| ____|  _ \
    # | |\/| | / _ \ | |_) | |  _|  _| | | | |
    # | |  | |/ ___ \|  _ <| |_| | |___| |_| |
    # |_|  |_/_/   \_\_| \_\\____|_____|____/
    # Master branch was pushed or marged by develop branches
    - |
      if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        echo "[INFO] Master branch was pushed or marged by feature branches";
        aws cloudformation package --template-file template.yaml --s3-bucket ssnewserv-aws-billing-slack-bot --output-template-file output.yaml --region us-east-1;
        aws cloudformation deploy --template-file output.yaml --stack-name billing-bot --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --region us-east-1;
      fi

    #  ____  _   _ _     _       ____  _____ ___  _   _ _____ ____ _____ ____
    # |  _ \| | | | |   | |     |  _ \| ____/ _ \| | | | ____/ ___|_   _/ ___|
    # | |_) | | | | |   | |     | |_) |  _|| | | | | | |  _| \___ \ | | \___ \
    # |  __/| |_| | |___| |___  |  _ <| |__| |_| | |_| | |___ ___) || |  ___) |
    # |_|    \___/|_____|_____| |_| \_\_____\__\_\\___/|_____|____/ |_| |____/

    # Pull Requests was created for develop to master
    - |
      if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      fi

    #   ___  _   _ _  __   __  ____  _   _ ____  _   _ _____ ____
    #  / _ \| \ | | | \ \ / / |  _ \| | | / ___|| | | | ____|  _ \
    # | | | |  \| | |  \ V /  | |_) | | | \___ \| |_| |  _| | | | |
    # | |_| | |\  | |___| |   |  __/| |_| |___) |  _  | |___| |_| |
    #  \___/|_| \_|_____|_|   |_|    \___/|____/|_| |_|_____|____/

    # Feature branch was pushed
    - |
      if [ "$TRAVIS_BRANCH" != "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        echo "[INFO] Only Pushed";
        echo "[INFO] Nothing to do";
        echo "[INFO] Feature branch was pushed";
        echo "[INFO] Nothing to do anything";
      fi
